services:
  app-db:
    image: postgis/postgis:15-3.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_APP_PASSWORD}
      POSTGRES_USER: ${DB_APP_USERNAME}
      POSTGRES_DB: ${DB_APP_NAME}
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - private


  auth-db:
    image: postgis/postgis:15-3.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_AUTH_PASSWORD}
      POSTGRES_USER: ${DB_AUTH_USERNAME}
      POSTGRES_DB: ${DB_AUTH_NAME}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - private

  node-api:
    image: hassanattar/carx-node-api
    container_name: carx-node-api
    depends_on:
      - auth-db
      - app-db
    environment:
      # Only for use in dev environment
      NODE_ENV: production
      DB_AUTH_USERNAME: ${DB_AUTH_USERNAME}
      DB_AUTH_PASSWORD: ${DB_AUTH_PASSWORD}
      DB_AUTH_HOST: auth-db
      DB_AUTH_PORT: 5432
      DB_AUTH_DIALECT: postgres
      DB_AUTH_PROTOCOL: tcp
      DB_AUTH_NAME: ${DB_AUTH_NAME}
      DB_AUTH_MIN_POOL_SIZE: 5
      DB_AUTH_MAX_POOL_SIZE: 20
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      DB_APP_HOST: app-db
      DB_APP_PORT: 5432
      DB_APP_DIALECT: postgres
      DB_APP_PROTOCOL: tcp
      DB_APP_NAME: ${DB_APP_NAME}
      DB_APP_MIN_POOL_SIZE: 5
      DB_APP_MAX_POOL_SIZE: 20
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      OPENCAGE_API_KEY: ${OPENCAGE_API_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    restart: always
    volumes:
      - /var/www/carxapp.org/static:/home/node/app/build/static
    networks:
      - private
      - public
    ports:
      - "8000:8000"
volumes:
  app_db_data:
  auth_db_data:
  static-content:

networks:
  private:
  public: